FROM node:20-alpine
#Create app directory

WORKDIR /app

#Install app dependencies
COPY package*.json

RUN npm install

# Install nodemon globally

RUN npm install -g nodemon

# Copy app source code

COPY . .

#Use nodemon for hot reload

CMD ["nodemon", "--legacy-watch", "src/main.ts"]