services:
  auth-service:
   build:
      context: .
      dockerfile: Dockerfile.dev
   ports:
      - "3000:3000"
   volumes:
     - .:/app
     - /app/node_modules
   environment:
     - JWT_SECRET=${JWT_SECRET}
     - DATABASE_URL=${DATABASE_URL}
   command: npm run start:dev

