include: 
  - docker-compose.postgres.yml
services: 
  auth-service:
    build: .
    container_name: auth_service
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - prisma-network
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    command: sh -c "npx prisma migrate deploy && node dist/main.js"  
 