services:
  postgres:
    image: postgres:16.8
    container_name: auth_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
    - '5432:5432'
    networks:
      - prisma-network
    healthcheck:
      test: ["CMD-SHELL", "sh -c \"pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}\""]
      interval: 5s
      timeout: 2s
      retries: 20    
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'
    logging: 
      options: 
        max-size: "10m"
        max-file: "3"
        
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    networks:
      - prisma-network
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - postgres    
networks:
  prisma-network:

volumes:
  pgdata: