services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run start:dev
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
